### PR TITLE
Fix/double submit again

### LINKED ISSUE #1129: Double Clicking "Post" when leaving a review uploads it twice
1. Go to a beta map page
2. Write a review
3. Double click post
4. It gets posted twice

**Expected behavior** 
Review should only be posted once

**Desktop:**

- OS: Linux
- Browser: Firefox

### PR DESCRIPTION
**Pull request by AshenCinders**
fixes #1129 again... sorry

Playing around with settimeout I was able to for example post a review twice, even with the `loading` check.
The `tap` function gets called before the code in `next/error` meaning a user could press post again just after loading was set to false in tap.
I've fixed the cases where I could actually prompt a double submit/delete/etc, but there are a few other functions left that still set a bool to false in tap. Not sure If we want to change these, as well.

Also fixed some tooltips not showing cause directive was missing.

Regarding setting the disabled attribute on the buttons (which I also did in 2 previous PRs), it's not necessary.
But, it will gray out the button to give feedback to the user that it is currently not clickable.
If you want that behaviour, I can change those buttons so that they gray out when loading. But it's up to you.
Currently, some of them do, some of them don't.

### Checks

- [x] __!! DONT IGNORE ME !! I have ran `./create-migrations.sh <name>` and committed the migration if I've made DB schema changes__
- [x] I have included/updated tests where applicable (see [Testing](https://github.com/momentum-mod/website/wiki/Testing))
- [x] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
- [x] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
- [x] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
- [x] All changes requested in review have been `fixup`ed into my original commits

### CODE REVIEW

**Comment by AshenCinders** [comment]
a ffs why would it make a merge commit

File: apps/frontend/src/app/components/map-review/map-review-form.component.ts [hunk 1]
```diff
@@ -141,39 +141,36 @@ export class MapReviewFormComponent {
...
+      next: () => {
+        this.reviewPosted.next();
+        this.messageService.add({
+          severity: 'success',
+          summary: `${this.editing ? 'Updated' : 'Posted'} map review for ${
+            this.map.name
+          }`
+        });
+        this.form.reset();
+        this.loading = false;
```
Comment (tsa96) [inline apps/frontend/src/app/components/map-review/map-review-form.component.ts:154]: Since we have a `take(1)` here the observable will complete after a single `next` or `error` call, so rather than do `this.loading: false` in both `next` and `error` callbacks, I'd do `complete: () => {this.loading = false;}`, bit easier to follow. Applies to other change as well.

**Review by tsa96 — CHANGES_REQUESTED** [review]

File: apps/frontend/src/app/components/map-review/map-review-form.component.ts (hunk 1 above)
Comment (AshenCinders) [reply apps/frontend/src/app/components/map-review/map-review-form.component.ts:154]: According to docs:
```
(property) complete?: () => void
A callback function that gets called by the producer if and when it has no more values to provide (by calling next callback function). This means that no error has happened. This callback can't be called more than one time, it can't be called if the error callback function have been called previously, nor it can't be called if the consumer has unsubscribed.
```

Though it seems I should be using `finalize` instead.
The change will end up being tap swapped for finalize.

**Review by tsa96 — APPROVED** [review]
