### PR TITLE
Responsive navbar, layout tweaks

### LINKED ISSUE #361: Menu button for mobile site is broken
download
This button is non-functional on the mobile layout.

### PR DESCRIPTION
**Pull request by tsa96**
Closes #361 

This button appears to have never worked in the first place and like it was designed for plain Bootstrap, this adds an Angular powered version and improves the layout. Should only have an affect on >960px wide screens.

Preview:

Also a minor tweak to vertical alignment:

Before:

After:

### CODE REVIEW

**Comment by tsa96** [comment]
the more I look at it the more pedantic and unnecessary the align-self-center change looks tbh, I just get nitpicky with vertical alignment

File: client/src/app/pages/main/nav/nav.component.ts [hunk 1]
```diff
@@ -6,18 +6,17 @@ import {Component, ElementRef, HostListener, ViewChild} from '@angular/core';
...
-  @ViewChild('mainNav', {static: false}) mainNav: ElementRef;
-  mainNavClass: string;
-  constructor() {
-    this.mainNavClass = '';
+
+  @ViewChild('mainNav', {static: false})
+  mainNav: ElementRef;
+  mainNavClass: string = '';
+
+  navbarOpen: boolean = false;
```
Comment (Gocnak) [inline client/src/app/pages/main/nav/nav.component.ts]: Why get rid of the constructor for setting these values?

File: client/src/app/pages/main/nav/nav.component.ts [hunk 2]
```diff
@@ -6,18 +6,17 @@ import {Component, ElementRef, HostListener, ViewChild} from '@angular/core';
...
 export class NavComponent {
-
   @HostListener('window:scroll', [])
   onWindowScroll() {
-    if (window.pageYOffset > 200) {
-      this.mainNavClass = 'navbar-shrink';
-    } else {
-      this.mainNavClass = '';
-    }
+    window.pageYOffset > 200 ? this.mainNavClass = 'navbar-shrink' : this.mainNavClass = '';
```
Comment (Gocnak) [inline client/src/app/pages/main/nav/nav.component.ts]:
```suggestion
    this.mainNavClass = window.pageYOffset > 200 ? 'navbar-shrink' : '';
```

File: client/src/app/pages/main/nav/nav.component.ts (hunk 1 above)
Comment (tsa96) [reply client/src/app/pages/main/nav/nav.component.ts]: I'm... not sure. Not used to using Typescript properly I guess, confusing myself

Comment (Gocnak) [reply client/src/app/pages/main/nav/nav.component.ts]: That's okay. We initialize all values in the constructor, along with putting all of variable declarations above it. See [the profile component](https://github.com/momentum-mod/website/blob/master/client/src/app/pages/dashboard/profile/user-profile.component.ts#L35) for an example of what to do here.

Comment (tsa96) [reply client/src/app/pages/main/nav/nav.component.ts]: Thanks, that's helpful. I've read up a bit, hopefully this last commit gets it right.
