### PR TITLE
Map submission DTOs

### LINKED ISSUE #827: Index signature handling on MapReviewSuggestionsDTO
Context: [website/pull/826/files#r1299166976](https://github.com/momentum-mod/website/pull/826/files#r1299166976)

We have some new DTO with index signatures which class-validation doesn't understand. Lets try [transform stuff to a `Map`](website/pull/826/files#r1299166976) (I don't know if Swagger and stuff will still work, we'll see), if that doesn't work, we could probably get by using a flat array storing the `track` and `Gamemode` properties on each element.

### PR DESCRIPTION
**Pull request by tsa96**
I should've done this earlier. This is every model and DTO needed for map submission, which should make it much easier for different people working on endpoints to work around each other.

Closes #827

### CODE REVIEW

File: apps/frontend/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts [hunk 1]
```diff
@@ -248,10 +247,11 @@ export class MapUploadFormComponent implements OnInit, AfterViewInit {
     let mapCreated = false;
     let mapID = -1;
 
-    const mapObject: CreateMap = {
+    const mapObject: any = {
+      // CreateMap = {
       name: this.name.value,
       fileName: this.name.value, // TODO: Proper filename field
-      type: this.type.value,
+      // type: this.type.value,
```
Comment (Gocnak) [inline apps/frontend/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts:254]: Commented?

**Review by Gocnak — APPROVED** [review]

File: apps/frontend/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts (hunk 1 above)
Comment (tsa96) [reply apps/frontend/src/app/pages/dashboard/maps/upload-form/map-upload-form.component.ts:254]: Probably getting rid of it, still slightly unsure if we want to store a `primaryMode` on the map or something. Ultimately this file is changing drastically in the future, don't mind leaving it a bit messy until I come back to it a couple weeks
